
var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in e)e.hasOwnProperty(k)&&(aa[k]=e[k]);var ba="./this.program";function ca(a,b){throw b;}var da=!1,l=!1,m=!1,ea=!1;da="object"===typeof window;l="function"===typeof importScripts;m="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ea=!da&&!m&&!l;var n=e.ENVIRONMENT_IS_PTHREAD||!1;n&&(p=e.buffer);
var _scriptDir="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;l?_scriptDir=self.location.href:m&&(_scriptDir=__filename);var q="";function fa(a){return e.locateFile?e.locateFile(a,q):q+a}var r,w,z,B;
if(m){q=l?require("path").dirname(q)+"/":__dirname+"/";r=function(a,b){z||(z=require("fs"));B||(B=require("path"));a=B.normalize(a);return z.readFileSync(a,b?null:"utf8")};w=function(a){a=r(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;});process.on("unhandledRejection",C);ca=
function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"};var ia;try{ia=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=ia.Worker}else if(ea)"undefined"!=typeof read&&(r=function(a){return read(a)}),w=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===
typeof quit&&(ca=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||l)l?q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",m?(r=function(a,b){z||(z=require("fs"));B||(B=require("path"));a=B.normalize(a);return z.readFileSync(a,b?null:"utf8")},w=function(a){a=r(a,!0);a.buffer||
(a=new Uint8Array(a));assert(a.buffer);return a}):(r=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));m&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ja=e.print||console.log.bind(console),D=e.printErr||console.warn.bind(console);
for(k in aa)aa.hasOwnProperty(k)&&(e[k]=aa[k]);aa=null;e.thisProgram&&(ba=e.thisProgram);e.quit&&(ca=e.quit);var ka,la=[],E,na;e.wasmBinary&&(na=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&C("no native wasm support detected");var F,G,oa,threadInfoStruct=0,selfThreadId=0,pa=!1;function assert(a,b){a||C("Assertion failed: "+b)}
function qa(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function H(a){return a?qa(I,a,void 0):""}
function ra(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var t=a.charCodeAt(++g);h=65536+((h&1023)<<10)|t&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var p,J,I,ta,K,L,ua,va=e.INITIAL_MEMORY||268435456;
if(n)F=e.wasmMemory,p=e.buffer;else if(e.wasmMemory)F=e.wasmMemory;else if(F=new WebAssembly.Memory({initial:va/65536,maximum:va/65536,shared:!0}),!(F.buffer instanceof SharedArrayBuffer))throw D("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),m&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");F&&(p=F.buffer);va=p.byteLength;var M=p;p=M;e.HEAP8=J=new Int8Array(M);e.HEAP16=ta=new Int16Array(M);e.HEAP32=K=new Int32Array(M);e.HEAPU8=I=new Uint8Array(M);e.HEAPU16=new Uint16Array(M);e.HEAPU32=L=new Uint32Array(M);e.HEAPF32=new Float32Array(M);e.HEAPF64=ua=new Float64Array(M);var wa=[],xa=[],ya=[],za=[];function Aa(){var a=e.preRun.shift();wa.unshift(a)}var N=0,Ba=null,Ca=null;e.preloadedImages={};e.preloadedAudios={};
function C(a){if(e.onAbort)e.onAbort(a);n&&console.error("Pthread aborting at "+Error().stack);D(a);pa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Da(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ea(){return Da("data:application/octet-stream;base64,")}var O="libh265decoder.wasm";Ea()||(O=fa(O));
function Fa(){try{if(na)return new Uint8Array(na);if(w)return w(O);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}function Ga(){return na||!da&&!l||"function"!==typeof fetch||Da("file://")?Promise.resolve().then(Fa):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Fa()})}
var P,Ia,Ka={10398:function(){throw"Canceled!";},10618:function(a,b){setTimeout(function(){Ja(a,b)},0)}};function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.xb;"number"===typeof c?void 0===b.Pa?G.get(c)():G.get(c)(b.Pa):c(void 0===b.Pa?null:b.Pa)}}}e.dynCall=function(a,b,c){var d;-1!=a.indexOf("j")?d=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):d=G.get(b).apply(null,c);return d};var Q=0,Ma=0,Na=0;
function Oa(a,b,c){Q=a|0;Na=b|0;Ma=c|0}e.registerPthreadPtr=Oa;function Pa(a,b){if(0>=a||a>J.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(K,R.La>>2),d=0;if(c==a&&Atomics.compareExchange(K,R.La>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(K,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}e._emscripten_futex_wake=Pa;
function Qa(a){if(n)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";K[a+12>>2]=0;(a=R.Ca[a])&&R.Wa(a.worker)}
var R={Sb:1,bc:{rb:0,sb:0},Fa:[],Ha:[],ac:function(){},Ab:function(){R.za=S(232);for(var a=0;58>a;++a)L[R.za/4+a]=0;K[R.za+12>>2]=R.za;a=R.za+156;K[a>>2]=a;var b=S(512);for(a=0;128>a;++a)L[b/4+a]=0;Atomics.store(L,R.za+104>>2,b);Atomics.store(L,R.za+40>>2,R.za);Atomics.store(L,R.za+44>>2,42);R.lb();Oa(R.za,!l,1);Ra(R.za)},Bb:function(){R.lb();R.receiveObjectTransfer=R.Hb;R.setThreadStatus=R.Kb;R.threadCancel=R.Nb;R.threadExit=R.Ob},lb:function(){R.La=Sa},Ca:{},Xa:[],Kb:function(){},qb:function(){for(;0<
R.Xa.length;)R.Xa.pop()();n&&threadInfoStruct&&Ta()},Ob:function(a){var b=Q|0;b&&(Atomics.store(L,b+4>>2,a),Atomics.store(L,b+0>>2,1),Atomics.store(L,b+60>>2,1),Atomics.store(L,b+64>>2,0),R.qb(),Pa(b+0,2147483647),Oa(0,0,0),threadInfoStruct=0,n&&postMessage({cmd:"exit"}))},Nb:function(){R.qb();Atomics.store(L,threadInfoStruct+4>>2,-1);Atomics.store(L,threadInfoStruct+0>>2,1);Pa(threadInfoStruct+0,2147483647);threadInfoStruct=selfThreadId=0;Oa(0,0,0);postMessage({cmd:"cancelDone"})},Mb:function(){for(var a in R.Ca){var b=
R.Ca[a];b&&b.worker&&R.Wa(b.worker)}R.Ca={};for(a=0;a<R.Fa.length;++a){var c=R.Fa[a];c.terminate()}R.Fa=[];for(a=0;a<R.Ha.length;++a)c=R.Ha[a],b=c.Aa,R.$a(b),c.terminate();R.Ha=[]},$a:function(a){if(a){if(a.threadInfoStruct){var b=K[a.threadInfoStruct+104>>2];K[a.threadInfoStruct+104>>2]=0;Ua(b);Ua(a.threadInfoStruct)}a.threadInfoStruct=0;a.Ya&&a.Ka&&Ua(a.Ka);a.Ka=0;a.worker&&(a.worker.Aa=null)}},Wa:function(a){delete R.Ca[a.Aa.tb];R.Fa.push(a);R.Ha.splice(R.Ha.indexOf(a),1);R.$a(a.Aa);a.Aa=void 0},
Hb:function(){},Cb:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.Aa&&(R.Za=a.Aa.threadInfoStruct);if(d.targetThread&&d.targetThread!=(Q|0)){var g=R.Ca[d.jc];g?g.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)Va();else if("spawnThread"===f)Wa(c.data);else if("cleanupThread"===f)Qa(d.thread);else if("killThread"===
f){c=d.thread;if(n)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";K[c+12>>2]=0;c=R.Ca[c];c.worker.terminate();R.$a(c);R.Ha.splice(R.Ha.indexOf(c.worker),1);c.worker.Aa=void 0}else if("cancelThread"===f){c=d.thread;if(n)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";R.Ca[c].worker.postMessage({cmd:"cancel"})}else"loaded"===
f?(a.loaded=!0,b&&b(a),a.Qa&&(a.Qa(),delete a.Qa)):"print"===f?ja("Thread "+d.threadId+": "+d.text):"printErr"===f?D("Thread "+d.threadId+": "+d.text):"alert"===f?alert("Thread "+d.threadId+": "+d.text):"exit"===f?a.Aa&&Atomics.load(L,a.Aa.tb+68>>2)&&R.Wa(a):"cancelDone"===f?R.Wa(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):D("worker sent an unknown command "+f));R.Za=void 0};a.onerror=function(c){D("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};
m&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:F,wasmModule:oa})},ub:function(){var a=fa("libh265decoder.worker.js");R.Fa.push(new Worker(a))},yb:function(){0==R.Fa.length&&(R.ub(),R.Cb(R.Fa[0]));return 0<R.Fa.length?R.Fa.pop():null},Ub:function(a){for(a=performance.now()+a;performance.now()<a;);}};e.establishStackSpace=function(a){Xa(a)};
e.getNoExitRuntime=function(){return noExitRuntime};var Ya;m?Ya=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:n?Ya=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Ya=dateNow:Ya=function(){return performance.now()};function Za(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function $a(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Za(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function ab(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function bb(a){if("/"===a)return"/";a=$a(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function cb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(m)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){C("randomDevice")}}
function db(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Za(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var eb=[];function fb(a,b){eb[a]={input:[],output:[],Ma:b};gb(a,hb)}
var hb={open:function(a){var b=eb[a.node.rdev];if(!b)throw new T(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ma.flush(a.tty)},flush:function(a){a.tty.Ma.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ma.kb)throw new T(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.Ma.kb(a.tty)}catch(t){throw new T(29);}if(void 0===h&&0===f)throw new T(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Ma.bb)throw new T(60);
try{for(var f=0;f<d;f++)a.tty.Ma.bb(a.tty,b[c+f])}catch(g){throw new T(29);}d&&(a.node.timestamp=Date.now());return f}},ib={kb:function(a){if(!a.input.length){var b=null;if(m){var c=Buffer.Qb?Buffer.Qb(256):new Buffer(256),d=0;try{d=z.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(sa(b)+1);b=ra(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},bb:function(a,b){null===b||10===b?(ja(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(qa(a.output,0)),a.output=[])}},jb={bb:function(a,b){null===b||10===b?(D(qa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(D(qa(a.output,0)),a.output=[])}},
U={Ba:null,Ea:function(){return U.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new T(63);U.Ba||(U.Ba={dir:{node:{Ga:U.va.Ga,Da:U.va.Da,lookup:U.va.lookup,Ua:U.va.Ua,rename:U.va.rename,unlink:U.va.unlink,rmdir:U.va.rmdir,readdir:U.va.readdir,symlink:U.va.symlink},stream:{Ja:U.wa.Ja}},file:{node:{Ga:U.va.Ga,Da:U.va.Da},stream:{Ja:U.wa.Ja,read:U.wa.read,write:U.wa.write,eb:U.wa.eb,mb:U.wa.mb,ob:U.wa.ob}},link:{node:{Ga:U.va.Ga,Da:U.va.Da,readlink:U.va.readlink},
stream:{}},fb:{node:{Ga:U.va.Ga,Da:U.va.Da},stream:kb}});c=lb(a,b,c,d);16384===(c.mode&61440)?(c.va=U.Ba.dir.node,c.wa=U.Ba.dir.stream,c.ua={}):32768===(c.mode&61440)?(c.va=U.Ba.file.node,c.wa=U.Ba.file.stream,c.ya=0,c.ua=null):40960===(c.mode&61440)?(c.va=U.Ba.link.node,c.wa=U.Ba.link.stream):8192===(c.mode&61440)&&(c.va=U.Ba.fb.node,c.wa=U.Ba.fb.stream);c.timestamp=Date.now();a&&(a.ua[b]=c);return c},Yb:function(a){if(a.ua&&a.ua.subarray){for(var b=[],c=0;c<a.ya;++c)b.push(a.ua[c]);return b}return a.ua},
Zb:function(a){return a.ua?a.ua.subarray?a.ua.subarray(0,a.ya):new Uint8Array(a.ua):new Uint8Array(0)},hb:function(a,b){var c=a.ua?a.ua.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ua,a.ua=new Uint8Array(b),0<a.ya&&a.ua.set(c.subarray(0,a.ya),0))},Ib:function(a,b){if(a.ya!=b)if(0==b)a.ua=null,a.ya=0;else{if(!a.ua||a.ua.subarray){var c=a.ua;a.ua=new Uint8Array(b);c&&a.ua.set(c.subarray(0,Math.min(b,a.ya)))}else if(a.ua||(a.ua=[]),a.ua.length>b)a.ua.length=b;
else for(;a.ua.length<b;)a.ua.push(0);a.ya=b}},va:{Ga:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ya:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.vb=4096;b.blocks=Math.ceil(b.size/b.vb);return b},Da:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&
(a.timestamp=b.timestamp);void 0!==b.size&&U.Ib(a,b.size)},lookup:function(){throw mb[44];},Ua:function(a,b,c,d){return U.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=nb(b,c)}catch(g){}if(d)for(var f in d.ua)throw new T(55);}delete a.parent.ua[a.name];a.name=c;b.ua[c]=a;a.parent=b},unlink:function(a,b){delete a.ua[b]},rmdir:function(a,b){var c=nb(a,b),d;for(d in c.ua)throw new T(55);delete a.ua[b]},readdir:function(a){var b=[".",".."],c;for(c in a.ua)a.ua.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=U.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new T(28);return a.link}},wa:{read:function(a,b,c,d,f){var g=a.node.ua;if(f>=a.node.ya)return 0;a=Math.min(a.node.ya-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ua||a.ua.subarray)){if(g)return a.ua=b.subarray(c,
c+d),a.ya=d;if(0===a.ya&&0===f)return a.ua=b.slice(c,c+d),a.ya=d;if(f+d<=a.ya)return a.ua.set(b.subarray(c,c+d),f),d}U.hb(a,f+d);if(a.ua.subarray&&b.subarray)a.ua.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.ua[f+g]=b[c+g];a.ya=Math.max(a.ya,f+d);return d},Ja:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ya);if(0>b)throw new T(28);return b},eb:function(a,b,c){U.hb(a.node,b+c);a.node.ya=Math.max(a.node.ya,b+c)},mb:function(a,b,c,d,f,g){assert(0===b);if(32768!==
(a.node.mode&61440))throw new T(43);a=a.node.ua;if(g&2||a.buffer!==p){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=S(g);c<g;)J[b+c++]=0;c=b;if(!c)throw new T(48);J.set(a,c)}else d=!1,c=a.byteOffset;return{hc:c,Tb:d}},ob:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new T(43);if(f&2)return 0;U.wa.write(a,b,0,d,c,!1);return 0}}},ob=null,pb={},qb=[],rb=1,sb=null,tb=!0,ub={},T=null,mb={};
function V(a,b){a=db("/",a);b=b||{};if(!a)return{path:"",node:null};var c={jb:!0,cb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.cb)throw new T(32);a=Za(a.split("/").filter(function(h){return!!h}),!1);var f=ob;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=nb(f,a[d]);c=$a(c+"/"+a[d]);f.Va&&(!g||g&&b.jb)&&(f=f.Va.root);if(!g||b.ib)for(g=0;40960===(f.mode&61440);)if(f=vb(c),c=db(ab(c),f),f=V(c,{cb:b.cb}).node,40<g++)throw new T(32);}return{path:c,node:f}}
function wb(a){for(var b;;){if(a===a.parent)return a=a.Ea.nb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sb.length}function nb(a,b){var c;if(c=(c=yb(a,"x"))?c:a.va.lookup?0:2)throw new T(c,a);for(c=sb[xb(a.id,b)];c;c=c.Fb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.va.lookup(a,b)}
function lb(a,b,c,d){a=new zb(a,b,c,d);b=xb(a.parent.id,a.name);a.Fb=sb[b];return sb[b]=a}var Ab={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(tb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Cb(a,b){try{return nb(a,b),20}catch(c){}return yb(a,"wx")}function Db(a){var b=4096;for(a=a||0;a<=b;a++)if(!qb[a])return a;throw new T(33);}function Eb(a,b){Fb||(Fb=function(){},Fb.prototype={});var c=new Fb,d;for(d in a)c[d]=a[d];a=c;b=Db(b);a.fd=b;return qb[b]=a}var kb={open:function(a){a.wa=pb[a.node.rdev].wa;a.wa.open&&a.wa.open(a)},Ja:function(){throw new T(70);}};function gb(a,b){pb[a]={wa:b}}
function Gb(a,b){var c="/"===b,d=!b;if(c&&ob)throw new T(10);if(!c&&!d){var f=V(b,{jb:!1});b=f.path;f=f.node;if(f.Va)throw new T(10);if(16384!==(f.mode&61440))throw new T(54);}b={type:a,ec:{},nb:b,Eb:[]};a=a.Ea(b);a.Ea=b;b.root=a;c?ob=a:f&&(f.Va=b,f.Ea&&f.Ea.Eb.push(b))}function Hb(a,b,c){var d=V(a,{parent:!0}).node;a=bb(a);if(!a||"."===a||".."===a)throw new T(28);var f=Cb(d,a);if(f)throw new T(f);if(!d.va.Ua)throw new T(63);return d.va.Ua(d,a,b,c)}function W(a){Hb(a,16895,0)}
function Ib(a,b,c){"undefined"===typeof c&&(c=b,b=438);Hb(a,b|8192,c)}function Jb(a,b){if(!db(a))throw new T(44);var c=V(b,{parent:!0}).node;if(!c)throw new T(44);b=bb(b);var d=Cb(c,b);if(d)throw new T(d);if(!c.va.symlink)throw new T(63);c.va.symlink(c,b,a)}function vb(a){a=V(a).node;if(!a)throw new T(44);if(!a.va.readlink)throw new T(28);return db(wb(a.parent),a.va.readlink(a))}
function Kb(a,b,c,d){if(""===a)throw new T(44);if("string"===typeof b){var f=Ab[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=$a(a);try{g=V(a,{ib:!(b&131072)}).node}catch(t){}}f=!1;if(b&64)if(g){if(b&128)throw new T(20);}else g=Hb(a,c,0),f=!0;if(!g)throw new T(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new T(54);if(!f&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Bb(b)||b&512)?31:yb(g,Bb(b)):44))throw new T(c);if(b&512){c=g;var h;"string"===typeof c?h=V(c,{ib:!0}).node:h=c;if(!h.va.Da)throw new T(63);if(16384===(h.mode&61440))throw new T(31);if(32768!==(h.mode&61440))throw new T(28);if(c=yb(h,"w"))throw new T(c);h.va.Da(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Eb({node:g,path:wb(g),flags:b,seekable:!0,position:0,wa:g.wa,Rb:[],error:!1},d);d.wa.open&&d.wa.open(d);!e.logReadFiles||b&1||(Lb||(Lb={}),a in Lb||(Lb[a]=1,D("FS.trackingDelegate error on read file: "+
a)));try{ub.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),ub.onOpenFile(a,g))}catch(t){D("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+t.message)}return d}function Mb(a,b,c){if(null===a.fd)throw new T(8);if(!a.seekable||!a.wa.Ja)throw new T(70);if(0!=c&&1!=c&&2!=c)throw new T(28);a.position=a.wa.Ja(a,b,c);a.Rb=[]}
function Nb(){T||(T=function(a,b){this.node=b;this.Jb=function(c){this.Ia=c};this.Jb(a);this.message="FS error"},T.prototype=Error(),T.prototype.constructor=T,[44].forEach(function(a){mb[a]=new T(a);mb[a].stack="<generic error, no stack>"}))}var Ob;function Pb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Qb(a,b,c){a=$a("/dev/"+a);var d=Pb(!!b,!!c);Rb||(Rb=64);var f=Rb++<<8|0;gb(f,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,t,u){for(var v=0,x=0;x<u;x++){try{var y=b()}catch(A){throw new T(29);}if(void 0===y&&0===v)throw new T(6);if(null===y||void 0===y)break;v++;h[t+x]=y}v&&(g.node.timestamp=Date.now());return v},write:function(g,h,t,u){for(var v=0;v<u;v++)try{c(h[t+v])}catch(x){throw new T(29);}u&&(g.node.timestamp=Date.now());return v}});
Ib(a,d,f)}var Rb,X={},Fb,Lb,Sb=void 0;function Tb(){Sb+=4;return K[Sb-4>>2]}function Y(a){a=qb[a];if(!a)throw new T(8);return a}
function Ub(a,b,c){if(n)return Z(1,1,a,b,c);Sb=c;try{var d=Y(a);switch(b){case 0:var f=Tb();return 0>f?-28:Kb(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Tb(),d.flags|=f,0;case 12:return f=Tb(),ta[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return K[Vb()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof X&&g instanceof T||C(g),-g.Ia}}
function Wb(a,b,c){if(n)return Z(2,1,a,b,c);Sb=c;try{var d=H(a),f=Tb();return Kb(d,b,f).fd}catch(g){return"undefined"!==typeof X&&g instanceof T||C(g),-g.Ia}}
function Xb(a,b,c){if(n)return Z(3,1,a,b,c);try{var d=Y(a);if(0>c||0>f)throw new T(28);if(null===d.fd)throw new T(8);if(1===(d.flags&2097155))throw new T(8);if(16384===(d.node.mode&61440))throw new T(31);if(!d.wa.read)throw new T(28);a="undefined"!==typeof f;if(!a)var f=d.position;else if(!d.seekable)throw new T(70);var g=d.wa.read(d,J,b,c,f);a||(d.position+=g);return g}catch(h){return"undefined"!==typeof X&&h instanceof T||C(h),-h.Ia}}
function Yb(){void 0===Yb.start&&(Yb.start=Date.now());return 1E3*(Date.now()-Yb.start)|0}
function Zb(){m||l||(ka||(ka={}),ka["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ka["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,D("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function $b(a,b,c){if(0>=a||a>J.length||a&1)return-28;if(da){if(Atomics.load(K,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(K,R.La>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(K,R.La>>2,0),-73;d=Atomics.exchange(K,R.La>>2,0);if(0==d)break;Va();if(Atomics.load(K,a>>2)!=b)return-6;Atomics.exchange(K,R.La>>2,a)}return 0}a=Atomics.wait(K,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function Z(a,b){for(var c=arguments.length-2,d=ac(),f=bc(8*c),g=f>>3,h=0;h<c;h++)ua[g+h]=arguments[2+h];c=cc(a,c,f,b);Xa(d);return c}var dc=[],ec=[],fc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function hc(a){a=2<a?H(a):a;return fc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function ic(a,b,c){var d=hc(a);if(!d)return-4;d.Ta&&(K[d.Ta>>2]=b,K[d.Ta+4>>2]=c);if(d.pb||!d.Wb)d.pb&&(d=d.pb),a=!1,d.Sa&&d.Sa.Ra&&(a=d.Sa.Ra.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Sa.Ra.viewport(0,0,b,c);else{if(d.Ta){a=a?H(a):"";d=K[d.Ta+8>>2];var f=ac(),g=bc(12),h=0;if(a){h=sa(a)+1;var t=S(h);ra(a,I,t,h);h=t}K[g>>2]=h;K[g+4>>2]=b;K[g+8>>2]=c;jc(0,d,657457152,0,h,g);Xa(f);return 1}return-4}return 0}
function kc(a,b,c){return n?Z(4,1,a,b,c):ic(a,b,c)}function lc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,h){b.drawElementsInstancedANGLE(c,d,f,g,h)})}
function mc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function nc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function oc(a){a||(a=pc);if(!a.zb){a.zb=!0;var b=a.Ra;lc(b);mc(b);nc(b);b.Xb=b.getExtension("EXT_disjoint_timer_query");b.dc=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var pc,qc=["default","low-power","high-performance"],rc={};function sc(){if(!tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in rc)a[b]=rc[b];var c=[];for(b in a)c.push(b+"="+a[b]);tc=c}return tc}var tc;
function uc(a){if(n)return Z(5,1,a);try{var b=Y(a);if(null===b.fd)throw new T(8);b.ab&&(b.ab=null);try{b.wa.close&&b.wa.close(b)}catch(c){throw c;}finally{qb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof X&&c instanceof T||C(c),c.Ia}}function vc(a,b){if(n)return Z(6,1,a,b);try{var c=Y(a);J[b>>0]=c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof X&&d instanceof T||C(d),d.Ia}}
function wc(a,b,c,d,f){if(n)return Z(7,1,a,b,c,d,f);try{var g=Y(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Mb(g,a,d);Ia=[g.position>>>0,(P=g.position,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];K[f>>2]=Ia[0];K[f+4>>2]=Ia[1];g.ab&&0===a&&0===d&&(g.ab=null);return 0}catch(h){return"undefined"!==typeof X&&h instanceof T||C(h),h.Ia}}
function xc(a,b,c,d){if(n)return Z(8,1,a,b,c,d);try{a:{for(var f=Y(a),g=a=0;g<c;g++){var h=f,t=K[b+8*g>>2],u=K[b+(8*g+4)>>2],v=void 0;if(0>u||0>v)throw new T(28);if(null===h.fd)throw new T(8);if(0===(h.flags&2097155))throw new T(8);if(16384===(h.node.mode&61440))throw new T(31);if(!h.wa.write)throw new T(28);h.seekable&&h.flags&1024&&Mb(h,0,2);var x="undefined"!==typeof v;if(!x)v=h.position;else if(!h.seekable)throw new T(70);var y=h.wa.write(h,J,t,u,v,void 0);x||(h.position+=y);try{if(h.path&&ub.onWriteToFile)ub.onWriteToFile(h.path)}catch(ma){D("FS.trackingDelegate['onWriteToFile']('"+
h.path+"') threw an exception: "+ma.message)}var A=y;if(0>A){var Ha=-1;break a}a+=A}Ha=a}K[d>>2]=Ha;return 0}catch(ma){return"undefined"!==typeof X&&ma instanceof T||C(ma),ma.Ia}}
function Wa(a){if(n)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=R.yb();if(void 0!==b.Aa)throw"Internal error!";if(!a.Na)throw"Internal error, no pthread ptr!";R.Ha.push(b);for(var c=S(512),d=0;128>d;++d)K[c+4*d>>2]=0;var f=a.Ka+a.Oa;d=R.Ca[a.Na]={worker:b,Ka:a.Ka,Oa:a.Oa,Ya:a.Ya,tb:a.Na,threadInfoStruct:a.Na};var g=d.threadInfoStruct>>2;Atomics.store(L,g,0);Atomics.store(L,g+1,0);Atomics.store(L,g+2,0);Atomics.store(L,g+17,a.detached);Atomics.store(L,
g+26,c);Atomics.store(L,g+12,0);Atomics.store(L,g+10,d.threadInfoStruct);Atomics.store(L,g+11,42);Atomics.store(L,g+27,a.Oa);Atomics.store(L,g+21,a.Oa);Atomics.store(L,g+20,f);Atomics.store(L,g+29,f);Atomics.store(L,g+30,a.detached);Atomics.store(L,g+32,a.rb);Atomics.store(L,g+33,a.sb);c=yc()+40;Atomics.store(L,g+44,c);b.Aa=d;var h={cmd:"run",start_routine:a.Lb,arg:a.Pa,threadInfoStruct:a.Na,selfThreadId:a.Na,parentThreadId:a.Gb,stackBase:a.Ka,stackSize:a.Oa};b.Qa=function(){h.time=performance.now();
b.postMessage(h,a.Pb)};b.loaded&&(b.Qa(),delete b.Qa)}function zc(){return Q|0}e._pthread_self=zc;
function Ac(a,b){if(!a)return D("pthread_join attempted on a null thread pointer!"),71;if(n&&selfThreadId==a)return D("PThread "+a+" is attempting to join to itself!"),16;if(!n&&R.za==a)return D("Main thread "+a+" is attempting to join to itself!"),16;if(K[a+12>>2]!==a)return D("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(L,a+68>>2))return D("Attempted to join thread "+a+", which was already detached!"),28;for(Zb();;){var c=
Atomics.load(L,a>>2);if(1==c)return c=Atomics.load(L,a+4>>2),b&&(K[b>>2]=c),Atomics.store(L,a+68>>2,1),n?postMessage({cmd:"cleanupThread",thread:a}):Qa(a),0;if(n&&threadInfoStruct&&!Atomics.load(L,threadInfoStruct+60>>2)&&2==Atomics.load(L,threadInfoStruct+0>>2))throw"Canceled!";n||Va();$b(a,c,n?100:1)}}
function Bc(a){if(n)return Z(9,1,a);switch(a){case 30:return 16384;case 85:return I.length/16384;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;
case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;
case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}K[Vb()>>2]=28;return-1}function zb(a,b,c,d){a||(a=this);this.parent=a;this.Ea=a.Ea;this.Va=null;this.id=rb++;this.name=b;this.mode=c;this.va={};this.wa={};this.rdev=d}
Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Nb();sb=Array(4096);Gb(U,"/");W("/tmp");W("/home");W("/home/web_user");
(function(){W("/dev");gb(259,{read:function(){return 0},write:function(b,c,d,f){return f}});Ib("/dev/null",259);fb(1280,ib);fb(1536,jb);Ib("/dev/tty",1280);Ib("/dev/tty1",1536);var a=cb();Qb("random",a);Qb("urandom",a);W("/dev/shm");W("/dev/shm/tmp")})();W("/proc");W("/proc/self");W("/proc/self/fd");
Gb({Ea:function(){var a=lb("/proc/self","fd",16895,73);a.va={lookup:function(b,c){var d=qb[+c];if(!d)throw new T(8);b={parent:null,Ea:{nb:"fake"},va:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");var Cc=[null,Ub,Wb,Xb,kc,uc,vc,wc,xc,Bc];n||xa.push({xb:function(){Dc()}});
var Gc={d:function(a,b,c,d){C("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",c,d?H(d):"unknown function"])},s:Ub,r:Wb,K:Xb,C:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(n)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=R.Ca[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){C()},u:Yb,m:function(a,b,c){ec.length=0;var d;for(c>>=2;d=I[b++];)(d=105>d)&&c&1&&c++,ec.push(d?ua[c++>>1]:K[c]),++c;return Ka[a].apply(null,
ec)},F:Zb,o:function(){},f:$b,e:Pa,g:Ya,h:function(){return Na|0},n:function(){return Ma|0},y:function(a,b,c){I.copyWithin(a,b,b+c)},z:function(a,b,c){dc.length=b;c>>=3;for(var d=0;d<b;d++)dc[d]=ua[c+d];return(0>a?Ka[-a-1]:Cc[a]).apply(null,dc)},G:function(){C("OOM")},A:function(a,b,c){return hc(a)?ic(a,b,c):kc(a,b,c)},l:function(){},B:function(a,b){var c={};b>>=2;c.alpha=!!K[b];c.depth=!!K[b+1];c.stencil=!!K[b+2];c.antialias=!!K[b+3];c.premultipliedAlpha=!!K[b+4];c.preserveDrawingBuffer=!!K[b+5];
c.powerPreference=qc[K[b+6]];c.failIfMajorPerformanceCaveat=!!K[b+7];c.Db=K[b+8];c.cc=K[b+9];c.gb=K[b+10];c.wb=K[b+11];c.fc=K[b+12];c.ic=K[b+13];a=hc(a);if(!a||c.wb)c=0;else if(a=a.getContext("webgl",c)){b=S(8);K[b+4>>2]=Q|0;var d={$b:b,attributes:c,version:c.Db,Ra:a};a.canvas&&(a.canvas.Sa=d);("undefined"===typeof c.gb||c.gb)&&oc(d);c=b}else c=0;return c},H:function(a,b){var c=0;sc().forEach(function(d,f){var g=b+c;f=K[a+4*f>>2]=g;for(g=0;g<d.length;++g)J[f++>>0]=d.charCodeAt(g);J[f>>0]=0;c+=d.length+
1});return 0},I:function(a,b){var c=sc();K[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});K[b>>2]=d;return 0},j:uc,J:vc,v:wc,q:xc,t:function(a){var b=Date.now();K[a>>2]=b/1E3|0;K[a+4>>2]=b%1E3*1E3|0;return 0},x:function(){R.Ab()},a:F,D:function(a){var b=R.Xa.pop();a&&b()},E:function(a,b){R.Xa.push(function(){G.get(a)(b)})},i:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return D("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return D("pthread_create called with a null thread pointer!"),
28;var f=[];if(n&&0===f.length)return Ec(687865856,a,b,c,d);var g=0,h=0,t=0,u=0;if(b){var v=K[b>>2];v+=81920;g=K[b+8>>2];h=0!==K[b+12>>2];if(0===K[b+16>>2]){var x=K[b+20>>2],y=K[b+24>>2];t=b+20;u=b+24;var A=R.Za?R.Za:Q|0;if(t||u)if(A)if(K[A+12>>2]!==A)D("pthread_getschedparam attempted on thread "+A+", which does not point to a valid thread, or does not exist anymore!");else{var Ha=Atomics.load(L,A+128>>2);A=Atomics.load(L,A+132>>2);t&&(K[t>>2]=Ha);u&&(K[u>>2]=A)}else D("pthread_getschedparam called with a null thread pointer!");
t=K[b+20>>2];u=K[b+24>>2];K[b+20>>2]=x;K[b+24>>2]=y}else t=K[b+20>>2],u=K[b+24>>2]}else v=2097152;(b=0==g)?g=Fc(16,v):(g-=v,assert(0<g));x=S(232);for(y=0;58>y;++y)L[(x>>2)+y]=0;K[a>>2]=x;K[x+12>>2]=x;a=x+156;K[a>>2]=a;c={Ka:g,Oa:v,Ya:b,rb:t,sb:u,detached:h,Lb:c,Na:x,Gb:Q|0,Pa:d,Pb:f};n?(c.Vb="spawnThread",postMessage(c,f)):Wa(c);return 0},p:function(a,b){return Ac(a,b)},c:zc,w:function(){},k:Bc};
(function(){function a(f,g){e.asm=f.exports;G=e.asm.L;oa=g;n||(N--,e.monitorRunDependencies&&e.monitorRunDependencies(N),0==N&&(null!==Ba&&(clearInterval(Ba),Ba=null),Ca&&(f=Ca,Ca=null,f())))}function b(f){a(f.instance,f.module)}function c(f){return Ga().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){D("failed to asynchronously prepare wasm: "+g);C(g)})}var d={a:Gc};n||(assert(!n,"addRunDependency cannot be used in a pthread worker"),N++,e.monitorRunDependencies&&e.monitorRunDependencies(N));
if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return D("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(na||"function"!==typeof WebAssembly.instantiateStreaming||Ea()||Da("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){D("wasm streaming compile failed: "+g);D("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Dc=e.___wasm_call_ctors=function(){return(Dc=e.___wasm_call_ctors=e.asm.M).apply(null,arguments)};e._init_decoder=function(){return(e._init_decoder=e.asm.N).apply(null,arguments)};e._uninit_decoder=function(){return(e._uninit_decoder=e.asm.O).apply(null,arguments)};e._decode=function(){return(e._decode=e.asm.P).apply(null,arguments)};e._set_log_level=function(){return(e._set_log_level=e.asm.Q).apply(null,arguments)};e._main=function(){return(e._main=e.asm.R).apply(null,arguments)};
var Vb=e.___errno_location=function(){return(Vb=e.___errno_location=e.asm.S).apply(null,arguments)},Ua=e._free=function(){return(Ua=e._free=e.asm.T).apply(null,arguments)},S=e._malloc=function(){return(S=e._malloc=e.asm.U).apply(null,arguments)},yc=e._emscripten_get_global_libc=function(){return(yc=e._emscripten_get_global_libc=e.asm.V).apply(null,arguments)};e.___em_js__initPthreadsJS=function(){return(e.___em_js__initPthreadsJS=e.asm.W).apply(null,arguments)};
var ac=e.stackSave=function(){return(ac=e.stackSave=e.asm.X).apply(null,arguments)},Xa=e.stackRestore=function(){return(Xa=e.stackRestore=e.asm.Y).apply(null,arguments)},bc=e.stackAlloc=function(){return(bc=e.stackAlloc=e.asm.Z).apply(null,arguments)},Fc=e._memalign=function(){return(Fc=e._memalign=e.asm._).apply(null,arguments)};e._emscripten_main_browser_thread_id=function(){return(e._emscripten_main_browser_thread_id=e.asm.$).apply(null,arguments)};
var Ta=e.___pthread_tsd_run_dtors=function(){return(Ta=e.___pthread_tsd_run_dtors=e.asm.aa).apply(null,arguments)},Va=e._emscripten_main_thread_process_queued_calls=function(){return(Va=e._emscripten_main_thread_process_queued_calls=e.asm.ba).apply(null,arguments)};e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.ca).apply(null,arguments)};
var Ra=e._emscripten_register_main_browser_thread_id=function(){return(Ra=e._emscripten_register_main_browser_thread_id=e.asm.da).apply(null,arguments)},Ja=e._do_emscripten_dispatch_to_thread=function(){return(Ja=e._do_emscripten_dispatch_to_thread=e.asm.ea).apply(null,arguments)};e._emscripten_async_run_in_main_thread=function(){return(e._emscripten_async_run_in_main_thread=e.asm.fa).apply(null,arguments)};
e._emscripten_sync_run_in_main_thread=function(){return(e._emscripten_sync_run_in_main_thread=e.asm.ga).apply(null,arguments)};e._emscripten_sync_run_in_main_thread_0=function(){return(e._emscripten_sync_run_in_main_thread_0=e.asm.ha).apply(null,arguments)};e._emscripten_sync_run_in_main_thread_1=function(){return(e._emscripten_sync_run_in_main_thread_1=e.asm.ia).apply(null,arguments)};
e._emscripten_sync_run_in_main_thread_2=function(){return(e._emscripten_sync_run_in_main_thread_2=e.asm.ja).apply(null,arguments)};e._emscripten_sync_run_in_main_thread_xprintf_varargs=function(){return(e._emscripten_sync_run_in_main_thread_xprintf_varargs=e.asm.ka).apply(null,arguments)};e._emscripten_sync_run_in_main_thread_3=function(){return(e._emscripten_sync_run_in_main_thread_3=e.asm.la).apply(null,arguments)};
var Ec=e._emscripten_sync_run_in_main_thread_4=function(){return(Ec=e._emscripten_sync_run_in_main_thread_4=e.asm.ma).apply(null,arguments)};e._emscripten_sync_run_in_main_thread_5=function(){return(e._emscripten_sync_run_in_main_thread_5=e.asm.na).apply(null,arguments)};e._emscripten_sync_run_in_main_thread_6=function(){return(e._emscripten_sync_run_in_main_thread_6=e.asm.oa).apply(null,arguments)};
e._emscripten_sync_run_in_main_thread_7=function(){return(e._emscripten_sync_run_in_main_thread_7=e.asm.pa).apply(null,arguments)};var cc=e._emscripten_run_in_main_runtime_thread_js=function(){return(cc=e._emscripten_run_in_main_runtime_thread_js=e.asm.qa).apply(null,arguments)},jc=e.__emscripten_call_on_thread=function(){return(jc=e.__emscripten_call_on_thread=e.asm.ra).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.sa).apply(null,arguments)};
e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.ta).apply(null,arguments)};var Sa=e._main_thread_futex=162452;
e.addFunction=function(a,b){var c=G;if(!E){E=new WeakMap;for(var d=0;d<c.length;d++){var f=c.get(d);f&&E.set(f,d)}}if(E.has(a))a=E.get(a);else{if(la.length)d=la.pop();else{d=c.length;try{c.grow(1)}catch(u){if(!(u instanceof RangeError))throw u;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}}try{c.set(d,a)}catch(u){if(!(u instanceof TypeError))throw u;if("function"===typeof WebAssembly.Function){var g={i:"i32",j:"i64",f:"f32",d:"f64"},h={parameters:[],results:"v"==b[0]?[]:[g[b[0]]]};for(f=
1;f<b.length;++f)h.parameters.push(g[b[f]]);b=new WebAssembly.Function(h,a)}else{g=[1,0,1,96];h=b.slice(0,1);b=b.slice(1);var t={i:127,j:126,f:125,d:124};g.push(b.length);for(f=0;f<b.length;++f)g.push(t[b[f]]);"v"==h?g.push(0):g=g.concat([1,t[h]]);g[1]=g.length-2;b=new Uint8Array([0,97,115,109,1,0,0,0].concat(g,[2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0]));b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f}c.set(d,b)}E.set(a,d);a=d}return a};
e.removeFunction=function(a){E.delete(G.get(a));la.push(a)};e.PThread=R;e.PThread=R;e._pthread_self=zc;e.wasmMemory=F;e.ExitStatus=ha;var Hc;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ca=function Ic(){Hc||Jc();Hc||(Ca=Ic)};
function Jc(){function a(){if(!Hc&&(Hc=!0,e.calledRun=!0,!pa)){e.noFSInit||Ob||(Ob=!0,Nb(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Qb("stdin",e.stdin):Jb("/dev/tty","/dev/stdin"),e.stdout?Qb("stdout",null,e.stdout):Jb("/dev/tty","/dev/stdout"),e.stderr?Qb("stderr",null,e.stderr):Jb("/dev/tty1","/dev/stderr"),Kb("/dev/stdin","r"),Kb("/dev/stdout","w"),Kb("/dev/stderr","w"));La(xa);n||(tb=!1,La(ya));if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Kc){var b=e._main;try{var c=
b(0,0);if(!noExitRuntime||0!==c){if(!noExitRuntime){R.Mb();if(e.onExit)e.onExit(c);pa=!0}ca(c,new ha(c))}}catch(d){d instanceof ha||("unwind"==d?noExitRuntime=!0:((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),D("exception thrown: "+b),ca(1,d)))}finally{}}if(!n){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),za.unshift(b);La(za)}}}if(!(0<N)){if(!n){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Aa();
La(wa)}0<N||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=Jc;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Kc=!0;e.noInitialRun&&(Kc=!1);n||(noExitRuntime=!0);n?R.Bb():Jc();
